configs:
  secret:
    argocdServerAdminPassword: $2a$10$5vm8wXaSdbuff0m9l21JdevzXBzJFPCi8sy6OOnpZMAG.fOXL7jvO

dex:
  enabled: false

notifications:
  enabled: false 
server:
  service: 
    type: NodePort
    nodePortHttp: 31443